### ISSUE TITLE
Load APIs using filesystem

### ISSUE THREAD

**Issue by kand617** [api-collab/api-collab-server#32]
For the API Portal only solution, 
As an Admin I would like to provide my api definitions using a file system approach.

**Comment by sudhirtumati** [comment]
Two possible implementation approaches:

- Build a separate module which scans the file system and push using portal REST API
- Build it as part of the portal application itself

I prefer an external module. @kand617 @koushiknama what do you think?

**Comment by sudhirtumati** [comment]
Moved to [fs-uploader](https://github.com/api-collab/api-collab-fs-uploader) repo. Follow [here](https://github.com/api-collab/api-collab-fs-uploader/issues/1)
