### ISSUE TITLE
Search - Word Autocomplete

### ISSUE THREAD

**Issue by kand617** [api-collab/api-collab-server#36]
As a user, when I type my partial words in to search box, I would like the system to provide suggestions. This will free me from remembering exact names.....
Now given that I could use search operators such as `valu*`, the system suggesting the word would be a nicer user experience. 

Note this is not a prediction system like google search. But rather a simple word autocomplete.
For example:
`startD` would give `startDate`, `startDay`, `creditStartDate` etc

**Comment by sudhirtumati** [comment]
Storing the dictionary in database and querying it every time would be a overkill, I agree. At the same time, letting client manage it presents different set of issues
- When is the dictionary pushed to client? Once per session?
- How is it refreshed with any changes made on server? Should user reload page to get latest dictionary?

Does hibernate search offer any features to address this use-case? In my view, this should be explored first before any alternate solutions.

**Comment by kand617** [comment]
I could be wrong, but Hibernate Search functions work based off an entity and a search on attribute(s) can only return entities as a whole. This is useful if the aim of auto complete is based on the title (not our case).

With the client side approach,

- This dictionary can be stored in `local storage`, can be queried using if-modified-since approach
- The check for updates can be done if the last check was done `n minutes ago`. Maybe 15 minutes or more.

**Comment by kand617** [comment]
Actually I have another solution which might be a lot cleaner.

- Store the entire list on server side (persisted to a db(single row, single column), and maintained in memory on start up)
- Use a fuzzy search library on server side

Pros:
- Super simple, no complex api
- Don't need to worry about local storage size limits, compression, cache updates
- Easy to test

Cons
- More API traffic, but that should be ok
- Slightly larger heap on server side

**Comment by kand617** [comment]
@sudhirtumati you mentioned you know of a way to play around with Lucene index to. Care to suggest the alternative?

**Comment by sudhirtumati** [comment]
@kand617 Here you go. These might get you started
- https://dzone.com/articles/hibernate-search-based
- https://stackoverflow.com/questions/5361941/autocomplete-using-hibernate-search

**Comment by sudhirtumati** [comment]
https://wiki.apache.org/lucene-java/TheBasics

**Comment by kand617** [comment]
Issue resolved with PR #37 
Enhancements to the quality will be done by subsequent PRs
